---
version: '3'
volumes:
  db-data:
    external: false
  bundle-data:
    external: false
services:
  dev:
    build: "."
    container_name: counterfeit_dev
    command: 'tail -f /dev/null'
    volumes:
      - bundle-data:/usr/local/bundle:cached
      - .:/var/www:cached
    ports:
      - 4567:4567
