---
version: '2'
volumes:
  db-data:
    external: false
  bundle-data:
    external: false
services:
  dev:
    build: "."
    entrypoint: ".picobox/start"
    volumes:
    - ".:/var/www:cached"
    volumes_from:
    - bundle
    hostname: picobox
    ports:
    - 4567:4567
    - 3000:3000
  bundle:
    image: busybox
    volumes:
    - bundle-data:/usr/local/bundle:cached
